onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

minimumReleaseAge: 10080 # 10080 minutter = 7 dager

minimumReleaseAgeExclude:
  - '@navikt/*'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  msw: true

overrides:
  '@vitest/mocker@>=2.1.0 <4.1.11': ^4.1.11
  vitest@>=2.1.0 <4.1.11: ^4.1.11
