services:
  hm-formidler:
    build: .
    image: 'hm-formidler'
    ports:
      - '9000:5000'
    environment:
      NAIS_CLUSTER_NAME: 'dev-gcp'
      BIND_ADDRESS: ':5000'
      API_URL: 'http://localhost:4040'
      HM_ROLLER_URL: 'http://localhost:4040'
      HM_SOKNAD_API_URL: 'http://localhost:4040'
      USE_MSW: 'true'
