version: "3"
services:
  hm-formidler:
    build: .
    image: "hm-formidler"
    ports:
      - "5000:5000"
    environment:
      NAIS_CLUSTER_NAME: "labs-gcp"
      API_URL: "http://localhost:8083/api"
      DECORATOR_URL: "https://www.nav.no/dekoratoren/?context=samarbeidspartner"
      IDPORTEN_WELL_KNOWN_URL: "http://172.27.88.226:8080/default/.well-known/openid-configuration"
      TOKEN_X_WELL_KNOWN_URL: "http://172.27.88.226:8080/default/.well-known/openid-configuration"
      USE_MSW: "true"
