apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-formidler
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 5000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  prometheus:
    enabled: false
    path: /metrics
  envFrom:
    - secret: session-encrypt-key
  ingresses:
    - https://www.nav.no/hjelpemidler/formidler
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  env:
    - name: API_URL
      value: http://hm-soknadsbehandling-db.teamdigihot.svc.cluster.local
    - name: SOKNADSBEHANDLING_AUDIENCE
      value: prod-gcp:teamdigihot:hm-soknadsbehandling-db
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login?redirect=https://www.nav.no/hjelpemidler/formidler"
    - name: HM_ROLLER_URL
      value: http://hm-roller.teamdigihot.svc.cluster.local
    - name: HM_ROLLER_AUDIENCE
      value: prod-gcp:teamdigihot:hm-roller
    - name: SOKNAD_URL
      value: https://www.nav.no/hjelpemidler/digitalsoknadhjelpemidler
    - name: REDIRECT_URL
      value: https://www.nav.no/hjelpemidler/formidler
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: loginservice.nav.no
      rules:
        - application: hm-soknadsbehandling-db
        - application: hm-roller
        - application: nav-dekoratoren
          namespace: personbruker
