export enum SoknadStatus {
  VENTER_GODKJENNING = "VENTER_GODKJENNING",
  GODKJENT = "GODKJENT",
  SLETTET = "SLETTET",
  GODKJENT_MED_FULLMAKT = "GODKJENT_MED_FULLMAKT",
  UTLØPT = "UTLØPT",
  ENDELIG_JOURNALFØRT = "ENDELIG_JOURNALFØRT"
}
