export enum SoknadStatus {
  VENTER_GODKJENNING = 'VENTER_GODKJENNING',
  GODKJENT = 'GODKJENT',
  SLETTET = 'SLETTET',
  GODKJENT_MED_FULLMAKT = 'GODKJENT_MED_FULLMAKT',
  UTLØPT = 'UTLØPT',
  ENDELIG_JOURNALFØRT = 'ENDELIG_JOURNALFØRT',
  VEDTAKSRESULTAT_INNVILGET = 'VEDTAKSRESULTAT_INNVILGET',
  VEDTAKSRESULTAT_MUNTLIG_INNVILGET = 'VEDTAKSRESULTAT_MUNTLIG_INNVILGET',
  VEDTAKSRESULTAT_DELVIS_INNVILGET = 'VEDTAKSRESULTAT_DELVIS_INNVILGET',
  VEDTAKSRESULTAT_AVSLÅTT = 'VEDTAKSRESULTAT_AVSLÅTT',
  VEDTAKSRESULTAT_ANNET = 'VEDTAKSRESULTAT_ANNET',
  UTLEVERING_STARTET = 'UTLEVERING_STARTET',
}
