export interface Hast {
  hasteårsaker: Hasteårsak[]
  hastBegrunnelse: string | null
}

export enum Hasteårsak {
  'UTVIKLING_AV_TRYKKSÅR' = 'UTVIKLING_AV_TRYKKSÅR',
  'TERMINALPLEIE' = 'TERMINALPLEIE',
  'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES' = 'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES',
  'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES_V2' = 'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES_V2',
  'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES_V3' = 'UTSKRIVING_FRA_SYKEHUS_SOM_IKKE_KAN_PLANLEGGES_V3',
  'RASK_FORVERRING_AV_ALVORLIG_DIAGNOSE' = 'RASK_FORVERRING_AV_ALVORLIG_DIAGNOSE',
  'ANNET' = 'ANNET',
}
