export enum Kategori {
  AlarmOgVarslingshjelpemidler = 'Alarm- og varslingshjelpemidler',
  Arbeidsstoler = 'Arbeidsstoler',
  Ganghjelpemidler = 'Ganghjelpemidler',
  Hygienehjelpemidler = 'Hygienehjelpemidler',
  HørselsOgVarslingshjelpemidler = 'Hørsels- og varslingshjelpemidler',
  KalendereOgPlanleggingssystemer = 'Kalendere og planleggingssystemer',
  KjøreposerVarmeposerOgRegncape = 'Kjøreposer, varmeposer og regncape',
  Madrasser = 'Madrasser',
  ManuelleRullestoler = 'Manuelle rullestoler',
  PersonløftereOgSeil = 'Personløftere og seil',
  SengerOgSengebunner = 'Senger, sengebunner m.m.',
  Sitteputer = 'Sitteputer',
  SkliVendeOgFlytte = 'Skli, vende og flytte',
  TerskeleliminatorerOgRamper = 'Terskeleliminatorer og ramper',
  ElektriskeRullestoler = 'Elektriske rullestoler',
  Varmehjelpemidler = 'Varmehjelpemidler',
  OverflyttingVendingOgPosisjonering = 'Overflytting, vending og posisjonering',
  StolerMedOppreisingsfunksjon = 'Stoler med oppreisingsfunksjon',
}
