name: Build, deploy to labs-gcp and create release
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - DUMMY

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and build application
        run: |
          yarn install
          yarn build
      - name: Pre-deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . -t $IMAGE
          echo  "${GITHUB_TOKEN}" | docker login -u ${GITHUB_REPOSITORY} --password-stdin docker.pkg.github.com
          docker push ${IMAGE}
      - name: Deploy to labs-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: .nais/labs-gcp.yaml
          PRINT_PAYLOAD: true
