name: Deploy to prod-gcp
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release tag
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=docker.pkg.github.com/$GITHUB_REPOSITORY/$APPLICATION:$GITHUB_SHA
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          DEPLOY_SERVER: deploy.nais.io:443 # Workaround https://nav-it.slack.com/archives/C5KUST8N6/p1674573453174539?thread_ts=1674572577.446359&cid=C5KUST8N6
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          VAR: commit=${{ github.sha }}
      - name: Post-production
        uses: navikt/digihot-deploy/actions/post-production@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to labs-gcp-prod-mirror
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: .nais/labs-gcp-prod-mirror.yaml
          VAR: commit=${{ github.sha }}