name: Vulnerabilities scanning of dependencies
on: 
  push:
  schedule:
    - cron: "0 17 * * 0,4" # Kl 02:00 hver søndag og torsdag

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov